server:
  port: 8080
  max-http-header-size: 4048
  tomcat:
    max-http-form-post-size: 10MB

spring:
  resources:
    add-mappings: false
  mvc:

    throw-exception-if-no-handler-found: true
    view:
      prefix: /
      suffix: .html
  data:
    mongodb:
      uri: mongodb://someone:ping%40123@pings:20000/someone
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

tid:
springfox:
  documentation:
    swagger:
      v2: path=/swagger


logging:
  level:
    com.superjoy: debug
